#!/bin/sh

# find where script is located
DIR=$(cd $(dirname "$0"); pwd)

# copy over any saved changes
cp $DIR/mixxx-controls/KANE_QuNeo_scripts.js $DIR/mixxx/res/controllers/
cp $DIR/mixxx-controls/KANE_QuNeo.midi.xml $DIR/mixxx/res/controllers/

# run mixx
echo $1
$DIR/mixxx/mixxx $1 --resourcePath $DIR/mixxx/res/

