#!/bin/sh

rm ~/.mixxx/midi/QUNEO_MIDI_1.midi.xml
rm ~/.mixxx/midi/Midi_Through_Port-0.midi.xml
sudo cp ~/quneo-mixxx/QUNEO_MIDI_1.midi.xml ~/.mixxx/midi/
sudo cp ~/quneo-mixxx/KANE_QuNeo_scripts.js /usr/share/mixxx/midi/
sudo cp ~/quneo-mixxx/KANE_QuNeo.midi.xml /usr/share/mixxx/midi/
mixxx --midiDebug
