#!/bin/sh

# exports newest mixxx configs and music to given location
# must be called as the user with the mixxx configs in order to 
# get the proper .mixxx folder

# make sure there is a first arg
if [ -z $1 ]; then
	echo "usage: first arg is the target dir"
	return -1
fi

# requires location to export to as first arg $1
USB=$1
echo "EXPORTING CONFIGS TO URI: "$USB

# find where script is located
DIR=$(cd $(dirname "$0"); pwd)

# find out where the music dir is located
MUSICDIR=$(head -n 1 $DIR/musicdir)

# update this installation's information
cp -rf ~/.mixxx/ $DIR/../
cp -rvf $MUSICDIR/RealBest/added/ $DIR/../music/RealBest/

# copy most recent stuff to given arg's quneo-mixxx directory
mkdir -p $USB/quneo-mixxx/.mixxx
sudo cp -r $DIR/../.mixxx $USB/quneo-mixxx/
mkdir -p $USB/quneo-mixxx/music/RealBest/added
sudo cp -vr $DIR/../music/RealBest/added/ $USB/quneo-mixxx/music/RealBest/

