#!/bin/sh

# exports music to given location

# make sure there is a first arg
if [ -z $1 ]; then
	echo "usage: first arg is the target dir"
	return -1
fi

# requires location to export to as first arg $1
USB=$1
echo "EXPORTING MUSIC TO URI: "$USB

# find where script is located
DIR=$(cd $(dirname "$0"); pwd)

# find out where the music dir is located
MUSICDIR=$(head -n 1 $DIR/musicdir)

# update this installation's information
cp -rf $MUSICDIR/ $DIR/../

# copy most recent stuff to $1's quneo-mixxx directory
mkdir -p $USB/quneo-mixxx/music
rsync -av $DIR/../music/ $USB/quneo-mixxx/music/ --exclude=unsorted

