#!/bin/sh

# exports everything necessary to duplicate this version of quneo-mixxx on
# another computer. the only change necessary after this and running the
# install script is to set mixxx's music directory to wherever the music dir
# was placed.

# make sure there is a first arg
if [ -z $1 ]; then
	echo "usage: first arg is the target dir"
	return -1
fi

# requires location to export to as first arg $1
USB=$1
echo "EXPORTING QUNEO-MIXXX DIR TO URI: "$USB

# make root folder
mkdir -p $USB/quneo-mixxx

# find where script is located
DIR=$(cd $(dirname "$0"); pwd)

# export music and configs
$DIR/export-music $USB
$DIR/export-configs $USB

# copy whole quneo-mixxx folder to location, minus subdirs music/ mixxx/
# .git/ and ugly/
rsync -a $DIR/../../quneo-mixxx $USB/ --exclude=mixxx --exclude=.git --exclude=music --exclude=ugly
